export const SET_LOGIN = 'set_login'
export const SET_LOADING = 'set_loading'
export const SET_USER = 'set_user'
export const SET_RENDER = 'set_render'
export const SET_ORDER = 'set_order'
export const SET_POPUP = 'set_popup'